### ISSUE TITLE
TonApiClient 0.2.0 custom fetch ignored

### ISSUE THREAD

**Issue by IlyaSemenov** [tonkeeper/tonapi-js#201]
### Problem

In `@ton-api/client` 0.2.0, `TonApiClient` advertises to accept custom `fetch` implementation:
https://github.com/tonkeeper/tonapi-js/blob/bf39a176290429ce70b26c3470c24c585c6ecb19/packages/client/src/client.ts#L2732-L2737

However, this parameter is in fact ignored, custom fetch is only taken from global window object (really guys? `window`, not even `globalThis`?):
https://github.com/tonkeeper/tonapi-js/blob/bf39a176290429ce70b26c3470c24c585c6ecb19/packages/client/src/client.ts#L2808-L2810

### Reproduction

```ts
const tonApi = new TonApiClient({
  baseUrl: "https://tonapi.io",
  apiKey: config.ton.apiKey,
  fetch: (...args) => {
    console.log("I am fetch in ton api client") // This is never called
    return fetch(...args)
  },
}
```

### Workarounds

In 0.1.1, this used to work: `new TonApiClient({ customFetch: ... })`

In 0.2.0, the workaround is to directly update the inner http client:

```ts
const tonApi = new TonApiClient({ ... })
tonApi.http.providedFetch = ...
```

This is however not typed.

**Comment by mois-ilya** [comment]
Thank you for pointing this out and for such a detailed issue description! I’ve just released a beta version that should address this problem: [@ton-api/client@0.3.0-beta.0](https://www.npmjs.com/package/@ton-api/client/v/0.3.0-beta.0).

It would be great if you could test it and let us know if it resolves your issue or if there’s anything else that needs improvement. Your feedback would be incredibly helpful!

**Comment by IlyaSemenov** [comment]
@mois-ilya Thanks! I confirm that it works correctly in 0.3.0-beta.0.

**Comment by IlyaSemenov** [comment]
Can you please publish this as a non-beta, and also lax the allowed semver range for ton-adapter to allow client 0.3? Currently, I'm seeing these warnings:

```
.
└─┬ @ton-api/ton-adapter 0.2.0
  └── ✕ unmet peer @ton-api/client@^0.2.0: found 0.3.0-beta.0
```

**Comment by mois-ilya** [comment]
reelased
