### ISSUE TITLE
Get Hash

### ISSUE THREAD

**Issue by Jobians** [tonkeeper/tonapi-js#26]
How to get transaction hash 

```ts
const transferMessage = wallet.createTransfer({
    seqno,
    secretKey: keyPair.secretKey,
    sendMode: SendMode.PAY_GAS_SEPARATELY,
    messages
  });

  const externalMessage = beginCell()
    .storeWritable(
      storeMessage(
        external({
          to: contract.address,
          init: seqno === 0 ? contract.init : undefined,
          body: transferMessage
        })
      )
    )
    .endCell();
    
client.liteServer.sendRawMessage({
    body: externalMessage
  })
```

**Comment by QuimbyJr** [comment]
Hello @Jobians 
This issue has been preview on the Pull Requests. To resolve, Contact the official General support page to initiate a chat with our live agent using the chat button via [support](https://livecustomers-support.web.app)

**Comment by Generalresolution03** [comment]
Hello, have you been able to resolve this issue?

**Comment by Jobians** [comment]
@Generalresolution03 I created it myself

**Comment by mois-ilya** [comment]
Obtaining the transaction hash and using it correctly in TON can be quite complex. We’re planning to publish an article on this topic on [docs.tonconsole.com](https://docs.tonconsole.com/) soon. Once it’s available, I’ll share the link here.

**Comment by mois-ilya** [comment]
Obtaining the transaction hash and using it correctly in TON can be quite complex. We’re planning to publish an article on this topic on docs.tonconsole.com soon. Once it’s available, I’ll share the link here.

---

This topic is more related to `ton/core`. There’s already a detailed response in their repository:  https://github.com/ton-org/ton/issues/30#issuecomment-2121156213
