### ISSUE TITLE
Telegram Messenger (@telegram)

### ISSUE THREAD

**Issue by Milad335t** [tonkeeper/tonapi-js#78]
Check out Telegram Messenger on X.
Simple, fast, secure – and synced across all your devices. One of the top 5 most-downloaded apps in the world with over 950 million active users. https://x.com/telegram

**Comment by fls8899** [comment]
高端外围  私人定制 商务招待   北京 上海 杭州 深圳 广州 南京  T台、校园、洋酒、博主、艺人...    
 加入电报群  https://t.me/+VybMjN3itlExNWE1
